version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pr-user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pr-db
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: pr-user
      DB_PASSWORD: postgres
      DB_DATABASE: pr-db