version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - data:/data/db

  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3000:${WEB_PORT}
    depends_on:
      - db
    environment:
      - DB_HOST=db 
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - WEB_PORT=${API_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
volumes:
  data: {}