version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - data:/data/db

  db-test:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=api_test
    ports:
      - ${DB_TEST_PORT}:5432

  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${API_PORT}:3000
    depends_on:
      - db
      - db-test
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - API_PORT=${API_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - NODE_ENV=${NODE_ENV}
volumes:
  data: {}
